// Code generated by goctl. DO NOT EDIT.
// Source: user-manage.proto

package userManageClient

import (
	"context"

	"application/apps/user-manage/rpc/userManage"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Details            = userManage.Details
	FloatRange         = userManage.FloatRange
	IntRange           = userManage.IntRange
	Parents            = userManage.Parents
	Query              = userManage.Query
	User               = userManage.User
	UserBindRequest    = userManage.UserBindRequest
	UserBindResponse   = userManage.UserBindResponse
	UserInfoRequest    = userManage.UserInfoRequest
	UserInfoResponse   = userManage.UserInfoResponse
	UserListRequest    = userManage.UserListRequest
	UserListResponse   = userManage.UserListResponse
	UserUnbindRequest  = userManage.UserUnbindRequest
	UserUnbindResponse = userManage.UserUnbindResponse

	UserManage interface {
		Page(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
		Info(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		Bind(ctx context.Context, in *UserBindRequest, opts ...grpc.CallOption) (*UserBindResponse, error)
		Unbind(ctx context.Context, in *UserUnbindRequest, opts ...grpc.CallOption) (*UserUnbindResponse, error)
	}

	defaultUserManage struct {
		cli zrpc.Client
	}
)

func NewUserManage(cli zrpc.Client) UserManage {
	return &defaultUserManage{
		cli: cli,
	}
}

func (m *defaultUserManage) Page(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	client := userManage.NewUserManageClient(m.cli.Conn())
	return client.Page(ctx, in, opts...)
}

func (m *defaultUserManage) Info(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := userManage.NewUserManageClient(m.cli.Conn())
	return client.Info(ctx, in, opts...)
}

func (m *defaultUserManage) Bind(ctx context.Context, in *UserBindRequest, opts ...grpc.CallOption) (*UserBindResponse, error) {
	client := userManage.NewUserManageClient(m.cli.Conn())
	return client.Bind(ctx, in, opts...)
}

func (m *defaultUserManage) Unbind(ctx context.Context, in *UserUnbindRequest, opts ...grpc.CallOption) (*UserUnbindResponse, error) {
	client := userManage.NewUserManageClient(m.cli.Conn())
	return client.Unbind(ctx, in, opts...)
}
