// Code generated by goctl. DO NOT EDIT.
package types

type Details struct {
	Phone    string  `json:"phone"`
	Role     int64   `json:"role"`
	Height   float64 `json:"height"`
	Weight   float64 `json:"weight"`
	Age      int64   `json:"age"`
	Sex      int64   `json:"sex"`
	Smoke    bool    `json:"smoke"`
	Drink    bool    `json:"drink"`
	Exercise bool    `json:"exercise"`
}

type FloatRange struct {
	Gte float64 `form:"gte,optional"`
	Lte float64 `form:"lte,optional"`
}

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"userInfo"` //该用户基本信息
}

type GetUserManageInfoRequest struct {
	OpenId string `form:"openId,optional"`
	Uid    string `form:"uid,optional"`
}

type GetUserManageInfoResponse struct {
	Info UserManageInfo `json:"info"`
}

type IntRange struct {
	Gte int64 `form:"gte,optional"`
	Lte int64 `form:"lte,optional"`
}

type InviteResponse struct {
	InvitationCode string `json:"invitationCode"` //邀请码
	Expire         int    `json:"expire"`         //有效时间，以秒为单位
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token Token `json:"token"`
}

type Parents struct {
	Uid     string `json:"uid"`
	Note    string `json:"note"`
	Confirm bool   `json:"confirm"`
}

type Query struct {
	Note     string     `form:"note,optional"`
	Confirm  int64      `form:"confirm,optional"`
	Phone    string     `form:"phone,optional"`
	Role     int64      `form:"role,optional"`
	Height   FloatRange `form:"height,optional"`
	Weight   FloatRange `form:"weight,optional"`
	Age      IntRange   `form:"age,optional"`
	Sex      int64      `form:"sex,optional"`
	Smoke    int64      `form:"smoke,optional"`
	Drink    int64      `form:"drink,optional"`
	Exercise int64      `form:"exercise,optional"`
}

type RegisterRequest struct {
	Username       string `json:"username"`
	Password       string `json:"password"`
	InvitationCode string `json:"invitationCode"` //邀请码
}

type RegisterResponse struct {
	Token Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"` //过期时间戳
}

type UpdateUserInfoRequest struct {
	Nickname string `json:"nickname,optional"` //昵称
	Avatar   string `json:"avatar,optional"`   //头像地址
	Password string `json:"password,optional"` //密码
}

type UpdateUserInfoResponse struct {
	UserId string `json:"userId"` //用户id
}

type UserInfo struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Status   int64  `json:"status"`
}

type UserManageBindRequest struct {
	OpenId string `json:"openId"`
	Uid    string `json:"uid"`
}

type UserManageBindResponse struct {
	OpenId string `json:"openId"`
}

type UserManageInfo struct {
	OpenId    string    `json:"openId"`
	Uid       string    `json:"uid"`
	Details   Details   `json:"details"`
	Parents   []Parents `json:"parents"`
	ParentNum int64     `json:"parentNum"`
}

type UserManagePageRequest struct {
	Query    Query `form:"query,optional"`
	PageNum  int64 `form:"pageNum,default=1"`
	PageSize int64 `form:"pageSize,default=10"`
}

type UserManagePageResponse struct {
	List      []UserManageInfo `json:"list"`
	Length    int64            `json:"length"`
	TotalPage int64            `json:"totalPage"`
}

type UserManageUnbindRequest struct {
	OpenId string `json:"openId"`
	Uid    string `json:"uid"`
}

type UserManageUnbindResponse struct {
	OpenId string `json:"openId"`
}
