// Code generated by goctl. DO NOT EDIT.
package types

type GetUserInfoResponse struct {
	UserInfo UserInfo `json:"userInfo"` //该用户基本信息
}

type InviteResponse struct {
	InvitationCode string `json:"invitationCode"` //邀请码
	Expire         int    `json:"expire"`         //有效时间，以秒为单位
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token Token `json:"token"`
}

type RegisterRequest struct {
	Username       string `json:"username"`
	Password       string `json:"password"`
	InvitationCode string `json:"invitationCode"` //邀请码
}

type RegisterResponse struct {
	Token Token `json:"token"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UpdateUserInfoRequest struct {
	Nickname string `json:"nickname,optional"` //昵称
	Avatar   string `json:"avatar,optional"`   //头像地址
	Password string `json:"password,optional"` //密码
}

type UpdateUserInfoResponse struct {
	UserId string `json:"userId"` //用户id
}

type UserInfo struct {
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Status   int64  `json:"status"`
}
