// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"application/apps/user/rpc/internal/logic"
	"application/apps/user/rpc/internal/svc"
	"application/apps/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Invite(ctx context.Context, in *user.InvitationRequest) (*user.InvitationResponse, error) {
	l := logic.NewInviteLogic(ctx, s.svcCtx)
	return l.Invite(in)
}

func (s *UserServer) UpdateInfo(ctx context.Context, in *user.UpdateRequest) (*user.UpdateResponse, error) {
	l := logic.NewUpdateInfoLogic(ctx, s.svcCtx)
	return l.UpdateInfo(in)
}

func (s *UserServer) GetInfo(ctx context.Context, in *user.GetInfoRequest) (*user.GetInfoResponse, error) {
	l := logic.NewGetInfoLogic(ctx, s.svcCtx)
	return l.GetInfo(in)
}
